### PR TITLE
Move to Maven project based development

### LINKED ISSUE #48: Make repo Maven compatible
In most cases, the Java side of JPL may be updated/improved without the C side being touched.  This means one may want a more recent `jpl.jar` than the  official one in repos or SWI stable distribution.

Converting this repo into a Maven-compatible one, would ease this a lot. And we will be able to offer JPL Java API as an artifact on the web (without updating the whole SWI system). 

I would also make it better in terms of SE, as Maven is very standard today in the Java community. Most Java IDE (IntelliJ or Ecllipse) support Maven projects and make everything much easier.

This should be fairly easy, but part of the job is to refactor the sources into the standard Maven structure (there were some issues when doing that with CMAKE)

### LINKED ISSUE #62: Cleaning and fixing examples
The set of examples for JPL are under `examples/` subdir, both for  Java and Prolog cases. These are installed into `doc/packages/examples/jpl`.

However, they may be out-of-sync with the latest JPL updates and seems their scripts are too old.  Do they actually work?

Check and fix as needed.

### PR DESCRIPTION
**Pull request by ssardina**
- Important move to "modernise" the system by moving it to Maven-project repo. 
    - This included following the [Maven standard layout](https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html). This will allow better development with IDEs, which all support Maven for Java. Fixes #48
    - This will decouple the updates on the C and Java code. Most of the updates often happen at the Java code for the Java API. As a Maven project, users can get the latest `jpl.jar` via dependencies.

- Clean-up, fixed, updated, and extended pack of examples and refactored them into `src/examples`; so no Java code is outside the `src/` folder. Fixes #62

- Finally, upgraded version to 7.6.1 (Dict + Maven + Examples)

Note: tests passed and installation via CMAKE is as before, with same dir structures.

### CODE REVIEW

**Comment by JanWielemaker** [comment]
Looks promising, but also after restarting fresh, I get this ...

```
janw (linux; master *) 21_> ninja
ninja: error: 'packages/jpl/src/main/java/jpl.jar', needed by 'packages/jpl/src/test/java/jpltest-7.6.1.jar', missing and no known rule to make it
```

(after `cmake -G Ninja ..`)

**Comment by ssardina** [comment]
Ouch! Well you are very polite as there is not much promising when you run it and says just that! :-)

OK I totally forgot running `ninja`, I assumed, wrongly, that if `make` works with the files from CMAKE so will Ninja. Wrong.

Somehow Ninja is not getting that `jpltest.jar` needs to be done after `jpl.jar` has been created:

```cmake
add_dependencies(jpltest jpl_jar)
```

It is very interesting that `make` compiles wonderful but `ninja` does it. I had a look and couldn't figure out why, will see if I find why, this may not be an easy one...

Thanks for noting.

**Comment by ssardina** [comment]
@JanWielemaker , fixed it! Somehow the files produced Ninja do not do well the dependency among jar files, but I found out that `INCLUDE_JARS` can also refer to a JAR module in CMAKE so it is much nicer and I can just do `INCLUDE_JARS jpl_jar`

Works now on Ninja (on my side, at least).

**Comment by JanWielemaker** [comment]
> OK I totally forgot running `ninja`, I assumed, wrongly, that if `make` works with the files from CMAKE so will Ninja. Wrong.

In theory I guess this should be true.   In practice is it more like 99%.   If you do everything cleanly in CMake it works, but as you get closer to the edges it may fail.   Likewise one should test building inside the source tree (Macports insists on that :cry: ), building in a subdir and building outside.   It is also good practice to build outside as a user without write access to the source tree.   

Anyway, thanks a lot.  I hope this will make a lot of JPL users happier!

P.s.  Deleted `Changelog` and `make.bat`, so you can close these issues.

**Comment by ssardina** [comment]
Thanks Jan for the check and merge!

Yes, it is expected some things won't work 100% as these are all three different tools, CMAKE, ninja, make

Interesting what you said about different building practices from different locations. Let me make sure I get this right for the future:

1. **building in a subdir.** This is the standard way right via CMAKE? I mean building from say `<source>/build` ? This is what I do.
2. **building inside the source tree (Macports insists on that).** What? Not within a `build/` subdir? That is crazy, where will all CMAKE files go? everywhere? ouch! 
3. **It is also good practice to build outside as a user without write access to the source tree.** I guess this means totally outside and without write access? interesting, that would require adding another user I guess.

I could see how all of them will increase the changes that everything works...

**Comment by JanWielemaker** [comment]
> Let me make sure I get this right for the future:

You got it totally right (including the crazyness :smile: )

**Pull request merged**
