### PR TITLE
.html to .md so that they are actually readable

### PR DESCRIPTION
**Pull request by AndreasVolkmann**
I wanted to try JPL but found that the documentation was unreadable, as it was in the html format.

By simply renaming the files to .md github successfully renders the markup. 

I don't know if you want to keep the .html files as well.

### CODE REVIEW

**Comment by JanWielemaker** [comment]
The files are obviously HTML files, so renaming to an extension that doesn't match the content seems a bad idea.  Just open them in your browser after cloning or discuss with Github a possibility to show .html files properly rendered.

**Comment by ssardina** [comment]
What he suggested was that if we rename it to `.md`, Github will render well. But, I agree fully, html should stay as html. 

However, the fact is that all those html files are completely outdated and they go back to version 3.x. @anionic  has a much updated and clean doc for the 7.x version (https://jpl7.org/) of JPL. 

What I suggest is to delete everything that is old and setup a few markdown files with some information and pointers to the right documentation in jpl7.org. We do not want to maintain two documentation packages either.

I am working on a branch to cleanup old documentation (now as .html) and produce new updated markdown files.

**Comment by ssardina** [comment]
Here is the current state of doc clean-up, trying to update what was there (very very out-of-date) and extract anything from there that is relevant technically or for historical reasons:

https://github.com/ssardina-research/packages-jpl/tree/enhacement/README

**Comment by pmoura** [comment]
Try `pandoc`. Available at https://pandoc.org

**Pull request closed without merging**
