### PR TITLE
Refactoring + doc improvements + version to 7.6.0

### PR DESCRIPTION
**Pull request by ssardina**
- Refactored term methods from Util to Term
- Improved documentation in several places
- Added textual mode to print lists as [.....] via .toString()
- Upgraded JPL version to 7.6.0 (Java, C, and Prolog code)

All tests pass

### CODE REVIEW

**Comment by JanWielemaker** [comment]
Thanks for all the good work!  I don't have much opinion on JPL as I'm not familiar with conventions in the Java world.   When ready, just ask me to merge.  I'll quickly check there is nothing weird and all tests still run, merge and push.  @anionic may have more strategic opinions on this.

**Comment by ssardina** [comment]
My pleasure Jan, this my little way of giving back after SWI has given me so much across so many years (decades now!)

It is **now all done in this PR**. It's mostly documentation enrichment with this that were missing, in particular for those starting to use JPL, and there is a move of some methods from `Util` to `Term`, as they were all related to building and manipulating terms.

With this final touch plus the changes before (e.g.,Rational) I moved the version to 7.6.0 as @anionic suggested.

**Comment by JanWielemaker** [comment]
Great.  You've done a lot of typing!   Building gives a little glitch (currently building using OpenJDK 11):

```
org/jpl7/Util.java:171: warning: [dep-ann] deprecated item is not annotated with @Deprecated
	public static final boolean isList(Term term) {
	                            ^
Note: org/jpl7/fli/atom_t.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 warning
[1522/2400] Building Java objects for jpltest.jar
./org/jpl7/Util.java:171: warning: [dep-ann] deprecated item is not annotated with @Deprecated
	public static final boolean isList(Term term) {
	                            ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 warning
```

**Comment by ssardina** [comment]
ohhh interesting. That's why I wanted this to be checked on another system/install. 

I will look into this. Thanks.

**Comment by JanWielemaker** [comment]
I've added an @Deprecated at the place the compiler complained about.  Didn't want to hold the release which is needed for the Debian testing cycle and think it can't do much harm.  If I messed up anyway, just start a new PR.  Enjoy the weekend!

**Comment by ssardina** [comment]
@JanWielemaker , how do you get that output? Is it when running CMAKE? I am doing:

```
make -C packages/jpl clean  ; make VERBOSE=1 -j 8 `
```

I have seen a few minor issues like this in the code, but I am not getting warnings at compile time, so I want to hunt them all before pushing. I am using oracle JDK, but cannot be because of that I guess.

**Comment by ssardina** [comment]
Ohh now I see your latest message. No harm,it is minor. But want to clean up all glitches like that.

**Comment by JanWielemaker** [comment]
Guess it is related to the JDK version?  Did show up using just default built.

**Pull request merged**
