### PR TITLE
Downgraded small code to Java 1.7 for compatibility (removed lambda)

### PR DESCRIPTION
**Pull request by ssardina**
- Removed the use of lambda in Dict.java - replaced it with standard 1.7 code.

### CODE REVIEW

**Comment by JanWielemaker** [comment]
Thanks.  Branch wasn't in sync, so I cherry-picked the relevant commit.  Release build works again :)

**Comment by ssardina** [comment]
Great. Yes I thought about it. I did some doc pushes to `master`  after that branch.

I thought about re-basing the branch (and re-push it with --force) but I thought that GitHub allows you to do a REBASE+MERGE in the PR from the GUI itself, right? I though you were going to do so, to keep a linear history.

**Comment by JanWielemaker** [comment]
I often prefer to do the merge locally, so I can test before pushing.   A rebase would probably have worked too.  Anyway, we are getting close.  Thanks.

**Comment by ssardina** [comment]
OK cool, I get it. Makes sense, you check everything locally and then push. Good.

BTW, you must have seen that now that the repo is Maven-based, I set-up GitHub to compile automatically when pushing to master or PR to master. 

I also set-up [packaging in GitHub](https://github.com/SWI-Prolog/packages-jpl/packages) so one could easily get the latest Java API via Maven dependency automatically (as the Java API is expected to change much more than the C infrastructure) by just following instruction shere:

https://jpl7.org/DeploymentJava

All good, it is looking better and easier to use. I would just love to know who is using SWIPL via JPL, there seems to be more people than what I thought...

**Comment by JanWielemaker** [comment]
> I would just love to know who is using SWIPL via JPL, there seems to be more people than what I thought...

I have little clue.  Breaking JPL causes people to complain though :smile:   Many people seem to like embedding Prolog into something.  I'm not a fan of it.

**Comment by ssardina** [comment]
Are you suggesting an effective way to find out who is using JPL? Sounds good.

I understand why you are not a fan of it. :-) 

But I could see why people would like to use Prolog embedded. And Java is a very popular and mainstream language, in which an embedded Prolog section could make parts of the app much nicer, simpler, and maintainable. 

That's why I wanted to get JPL to an easily accessible framework. It could be a very powerful combination.

**Pull request closed without merging**
