### PR TITLE
Migrated JUNIT 3 to JUNIT 4 

### PR DESCRIPTION
**Pull request by ssardina**
These are the tests for Prolog inside Java

Now system is using JUNIT 4 and the very old test file has been integrated and removed.

The integration of the standalone tests (which are all JUNIT 4 anyways) will be handled separately as the tests need to be cleanly organized in "topics" (lists, variables, solutions, etc) 

This PR addresses issue #40

### CODE REVIEW

**Comment by JanWielemaker** [comment]
Thanks.  Merged using squash merge.   Will update web page for dependencies.

**Comment by JanWielemaker** [comment]
Could this be related? https://swi-prolog.discourse.group/t/java-jpl-cmake-test-errors/2177/3

**Comment by ssardina** [comment]
mmm ops! Yes could be yes. `hamcrest-core` may indeed be related to the new JUNIT4. 
Thanks for passing that post in the forum.

(Will check this tomorrow. I was working a lot today in the Rationals, it is almost done, I am doing check and seems to all work well!)

**Comment by JanWielemaker** [comment]
Thanks!   Do you follow the forum?

**Comment by ssardina** [comment]
Not really... I will follow this one though but best if you direct it to here; just cannot promise I can keep up with that! :-)

I am also re-structuring the whole organization of the test package for JPL, much cleaner now using TesSuites and all in JUNIT. There was a LOT of old code. 

Should I re-open this issue?

**Comment by JanWielemaker** [comment]
I'll forward stuff I think is for you :)   

> Should I re-open this issue?

No.  Please start a new PR.  Otherwise I have to do difficult things to make git happy again.

**Comment by ssardina** [comment]
Sorry sorry I meant re-open issue #40, not this PR.

**Comment by JanWielemaker** [comment]
:smile: I don't care about issues being reopened or not, as long as I can figure out what is going on.

**Pull request closed without merging**
