### PR TITLE
Enhacement/warnings hascode

### LINKED ISSUE #49: .equals() with no .hascode() in many classes
Many classes override .equals()`  (e.g., Atom, Compound), which makes total sense, but they do so without overriding `.hascode()` which breaks the contract and is something it should not be done and would cause problems when using collections, for example.

> You must override hashCode() in every class that overrides equals(). Failure to do so will result in a violation of the general contract for Object.hashCode(), which will prevent your class from functioning properly in conjunction with all hash-based collections, including HashMap, HashSet, and Hashtable.
(Joshua Bloch says on Effective Java)

Clear  short explanation: [Java: Why you should always override hashCode when overriding equals](https://programming.guide/java/overriding-hashcode-and-equals.html)

### PR DESCRIPTION
**Pull request by ssardina**
Here we go again! ;-)

**Fixes:**

- Fixed #49 all `.equals()` by adding corresponding `.hashcode()`. This is important, otherwise `Object.hascode()` contract is broken and lots of problems arise with Collections
- Fixed JRef: two `Variables` are the same not just because their textual name is the same; two  `X` coul be part of different queries!

**Improvements:**

- Many in the documentation. Updated old information, and added quite a bit for the user to understand JRef and Lists better.

**Minor/cosmetic/code quality:**

- Removed lots of non-dangerous but ugly warnings (e.g., redundant casting, overriding deprecated methods). Only 2 remains for generics that cannot be avoided.
- Start moving some files to more standard file conventions.

### CODE REVIEW

**Comment by JanWielemaker** [comment]
Thanks.  Looks all pretty innocent :)  Merged.  Do you get these (they are there a long time)

```
[420/463] Building Java objects for jpl_jar.jar
Note: org/jpl7/fli/atom_t.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
[425/463] Building Java objects for jpltest.jar
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

**Comment by ssardina** [comment]
Thanks Jan. Yes all innocent except for `.equals()` with no `.hashcode()` that was simple but long-standing "glitch". 

I don't get that warning. It is very strange, I cannot see `atom_t` using or overriding a deprecated API. It is indeed a very simple class with almost nothing....

I used to get many of that sort and other warnings, 30+. I cleaned them all up, now I got just 2 that are not possible to get rid of as they have to do with generics.

But, your compile and runner does have some magic. I remember when it used to load and run libraries that could never been loaded! ;-)

Strange...

**Comment by ssardina** [comment]
BTW, I changed to OpenJDK 11 and yes I also get that:

Now why do I get progress as % and you get the ratio `done/total`?

```shell
100%] Built target test_certificates
[100%] Linking C shared module libjpl.so
[100%] Built target plugin_libjpl
Note: org/jpl7/fli/atom_t.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
[100%] Generating CMakeFiles/jpl_jar.dir/java_class_filelist
[100%] Creating Java archive jpl-7.6.0.jar
[100%] Built target jpl_jar
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
[100%] Generating CMakeFiles/jpltest.dir/java_class_filelist
[100%] Creating Java archive jpltest.jar
[100%] Built target jpltest
```

**Comment by JanWielemaker** [comment]
> Now why do I get progress as % and you get the ratio `done/total`?

Because I use ninja to build instead of good old make.    Ninja gives a lot better build experience than make: faster, just gives progress on the same line unless there output of a command on stderr.  In that case it is printed, nicely separated from other concurrent commands.

Glad you can reproduce :)

**Comment by anionic** [comment]
Sorry, I've only just noticed how you've changed Variable equality: I maintain that "A Variable is equal to another if their names are the same and they are not anonymous" and fear that you are restoring one of Fred's original misconceptions ;-/

A Java-side Variable is just a lexical token; it is most definitely **not** any variable within the Prolog engine. The object identity of a Variable doesn't mean much at all, and it matters not whether two occurrences of a variable within a goal (say, `p(A, A)`) are represented by the same (identical) Variable object or by two same-named instances of Variable - they are just lexical tokens.

Comparing two Variables Java-side is a not-particularly-useful operation whose only consistent definition is based on equality of their names; your version of equality won't break anything important, but it is wrong! If necessary I can elaborate until you are convinced!

**Comment by ssardina** [comment]
Hi @anionic ,

Thanks for commenting on that and happy to move it back.

I was completing the `.hascode()` for every class that had a `.equals()` and then I thought this was a glitch, seems not and this was thought before. As you can imagine I am not aware of all much discussion that has happened in the past  haha

I can be convinced very easy don't worry. I am not going to fight for something  you know much more than me. ;-)

You are right that comparing `Variables` is not useful operation and would almost never will be done. But of course we want still something that is as close to the "correct" meaning even if not used much. I agree one will never compare `Variables`.

So, can you explain me what is the intended behavior of this code (which I included in unit testing but I can change of course):

```
       Variable v1 = new Variable("X");
        Variable v2 = new Variable("X");

        Term s1 = new Query("? = 5", v1).oneSolution().get("X");
        Term s2 = new Query("? = 15", v2).oneSolution().get("X");
```

It appears to me that you want `v1.equals(v2)` to be `True`, despite the fact that they refer to different bindings (one 5 the other 150? Is that correct? 

Seems you want to make them equal if they have the same textual name, full stop, is that correct?

**Pull request merged**
