### PR TITLE
Maven

### PR DESCRIPTION
**Pull request by javatlacati**
* Updating Maven branch to include latest changes
* Fixed compatibility problem in javadoc-maven-plugin in Java 13

Build still fails on windows due to #34

### CODE REVIEW

**Comment by JanWielemaker** [comment]
Thanks.   First, could you re-create this PR relative to a clean master?  It now has 15 mostly conflicting commits.   I understand the only real change is the added `pom.xml`.   I guess though that this file also needs to be installed, no (I know practically nothing about Java, so please be really explicit)?   I guess it also make sense to add a note in one of the documentation files?

For the good understanding, 8.0 is frozen.  Fixes and new stuff go into swipl-devel, 8.1.x.

**Comment by javatlacati** [comment]
Hello sir, I've actually cherry-picked all the commits from the master branch to make them even, the only real commit here is 1d342c1 all the other commits are already present at the master branch.

image

In such commit I've only added extra configuration parameters to prevent JavaDoc tool to fail in newer Java Versions (12, 13, 14). Adding the extra configuration doesn't break the build if you use older Java Versions (1.7,1.8).

image

**Comment by JanWielemaker** [comment]
I see.  This is a patch on the `maven` branch rather than on master.   I didn't even know this branch existed.    @ssardina Should it?   What is your recommendation here?   If possible I'd like to have one branch and only temporary topic branches and optionally a `stable` branch for backports to the stable version.

**Comment by ssardina** [comment]
Hi, just manage to get to this, sorry.

The `maven` branch was meant to be a "mirror" of master, but "Maven aware", that is, containing a file `pom.xml` file so that the JPL Java side `jpl.jar` can be deployed & used via the Maven system. The reason being that I wanted to have JPL easily available via systems like [JitPack](https://jitpack.io/). In that way, your Java-SWI application can get the "latest" `jpl.jar` version directly from the web, without the need to download and compiled. This was more relevant when I had JPL in my own fork so I did not have access to the official repo.

However, now that we have upgraded the official JPL, I think it makes no sense to have a dedicated maven branch for the above purposes. If one wants to use SWI inside Java, one would get the latest `jpl.jar` with the SWI distribution and that's it.  For those using SWIPL from a distribution (say Linux Mint) but who would like a more "updated" `jpl.jar`, we can provide such JAR file as a package in this repo.

HOWEVER, we may want to set-up JPL as a Maven project itself for "SE good practice" purposes, as Maven is very widely used in Java community, will provide a more standard source tree than the one being used now (organization of tests, sources, resources, etc),  facilitate compilation and deployment of jar file, etc.

I am tending towards YES, but would like to hear @anionic opinion first. Should I set-up the project as a Maven project?

**Comment by ssardina** [comment]
@javatlacati , I have sync the maven branch and incorporated your fix for javadoc, and also other improvements on POM. Will not merge this PR as to avoid repeated commits.

In the next phase I will make the master repo Maven compatible, so that this special branch is not necessary anymore. I will open another issue on that.

**Comment by JanWielemaker** [comment]
> Will not merge this PR as to avoid repeated commits.

Can't you rebase it?   I agree that is not always possible as the process sometimes leads to zillions of conflicts that are a bit too tedious to fix, but if that happens you can always abort the rebase.  The basics are as simple as checkout the `maven` branch and run

    git rebase master

**Comment by ssardina** [comment]
It comes from another branch that did not have a nice history, but really there is just one difference: an additional `pom.xml` file. 

Actually this paralell branch `maven` makes no sense. We should just include `pom.xml` in the master and that's it. It is just 1 file that would make the Java part of JPL maven aware.

**Comment by JanWielemaker** [comment]
Fine.  Let us do so!

**Comment by ssardina** [comment]
Yes I will soon do a very simple PR to add `pom.xml` to the master. With that, it will be trivial to generate a `jpl.jar` without any infrastructure and we can even use systems like JitPack that will connect o this repo and produce the JAR file.

The reason is that it will not be unusual that we update the Java side (`jpl.jar`) without touching anything on SWIPL or `libjpl` C part. In fact 99% of the time is like that (the only time I had to change C part was to add Rationals)

Just wanted to explain why we want Maven to re-generate updated `jpl.jar` Java API.

**Pull request closed without merging**
